Repository podcodar/webapp, pull requests merged in 2024-10, with the labels that each got.

#175 [fea] install and configure daisy UI
  bun.lockb
  package.json
  packages/components/NavBar.tsx
  packages/utils/classes.test.ts
  packages/utils/classes.ts
  packages/utils/types.ts
  tailwind.config.ts
Labels: dependencies, refactoring

#189 [ref] Migrate Footer component
  packages/components/Footer.tsx
Labels: refactoring

#196 [vitepress] Engineering Wiki
  bun.lockb
  docs/.vitepress/config.mts
  docs/.vitepress/theme/config.ts
  docs/.vitepress/theme/index.ts
  docs/index.md
  docs/src/guidelines/code-review.md
  docs/src/guidelines/coding-standards.md
  docs/src/guidelines/git-workflow.md
  docs/src/guidelines/index.md
  docs/src/guidelines/pull-requests.md
  docs/src/index.md
  docs/src/vitepress/api-examples.md
  docs/src/vitepress/index.md
  docs/src/vitepress/markdown-examples.md
  package.json
Labels: documentation

#198 [ref] Migrate CallToActionSection component
  bun.lockb
  packages/components/CallToActionSection.tsx
  packages/components/icons/Illustration.tsx
Labels: refactoring

#205 [ref] Migrate `MentoringSection` component to use TailwindCSS
  packages/components/MentoringSection.tsx
Labels: refactoring

#207 [ref] Migrate icons from chakra to tailwindcss
  biome.json
  packages/components/NavBar.tsx
  packages/components/SocialIconLinks.tsx
  packages/components/TechSection.tsx
  packages/components/WhyItWorksSection.tsx
  packages/components/icons/BRFlagIcon.tsx
  packages/components/icons/CssIcon.tsx
  packages/components/icons/DockerIcon.tsx
  packages/components/icons/GitIcon.tsx
  packages/components/icons/GithubIcon.tsx
  packages/components/icons/HtmlIcon.tsx
  packages/components/icons/Illustration.tsx
  packages/components/icons/JavaScriptIcon.tsx
  packages/components/icons/LinkedInIcon.tsx
  packages/components/icons/LinuxIcon.tsx
  packages/components/icons/Logo.tsx
  packages/components/icons/NextIcon.tsx
  packages/components/icons/NodeIcon.tsx
  packages/components/icons/PersonalizedLearningIcon.tsx
  packages/components/icons/PracticalLearningIcon.tsx
  packages/components/icons/PythonIcon.tsx
  packages/components/icons/ReactIcon.tsx
  packages/components/icons/ReduxIcon.tsx
  packages/components/icons/ShellIcon.tsx
  packages/components/icons/SqlIcon.tsx
  packages/components/icons/TeamworkIcon.tsx
  packages/components/icons/TechIcon.tsx
  packages/components/icons/TypeScriptIcon.tsx
  packages/components/icons/USFlagIcon.tsx
  packages/components/icons/WebPackIcon.tsx
Labels: refactoring

#209 [ref] Migrate TestimonialSection component
  next.config.js
  packages/components/TestimonialSection.tsx
Labels: refactoring

#212 [ref] migrate remaining components
  biome.json
  packages/components/Layout.tsx
  packages/components/Link.tsx
  packages/components/MemberCard.tsx
  packages/components/NavBar.tsx
  packages/components/RoadmapSection.tsx
  packages/components/SocialIconLinks.tsx
  packages/components/ToggleLanguage.tsx
  packages/components/ToggleThemeButton.tsx
  packages/features/i18n-context.tsx
Labels: refactoring

#216 [ref] Migrating the TeamPage from Chakra UI to Tailwind.
  packages/components/TeamPage.tsx
Labels: refactoring

#220 [ref] Migrating the not-found from Chakra UI to Tailwind.
  app/not-found.tsx
Labels: refactoring

#221 [ref] cleanup dependencies
  app/_app.tsx
  biome.json
  bun.lockb
  package.json
  packages/components/CallToActionSection.tsx
  packages/components/Footer.tsx
  packages/components/Link.tsx
  packages/components/MemberCard.tsx
  packages/components/MentoringSection.tsx
  packages/components/NavBar.tsx
  packages/components/Providers.tsx
  packages/components/RoadmapSection.tsx
  packages/components/Section.tsx
  packages/components/SkeletonMemberCard.tsx
  packages/components/SocialIconLinks.tsx
  packages/components/TeamPage.tsx
  packages/components/TechSection.tsx
  packages/components/TestimonialSection.tsx
  packages/components/ToggleLanguage.tsx
  packages/components/WhyItWorksSection.tsx
  packages/components/dialogs/CallToActionModal.tsx
  packages/entities/github.ts
  packages/entities/questions.ts
  packages/features/modal-context.tsx
  packages/hooks/useCustomToast.tsx
  packages/hooks/useEditingMode.tsx
  packages/hooks/useIsClient.tsx
  packages/locale/context.tsx
  packages/utils/react.tsx
Labels: refactoring

#224 Joel/ref/remove chakra UI dependencies
  bun.lockb
  package.json
  packages/components/NavBar.tsx
  packages/components/icons/CloseIcon.tsx
  packages/components/icons/HamburgerIcon.tsx
Labels: feature, refactoring

#211 [ref] Migrate RoadmapSection component
  packages/components/RoadmapSection.tsx
  packages/components/roadmapSection.module.css
Labels: refactoring
